# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc67cde636c8db09cd3b7028ffc06440aa5e1b68c756e1b115a828bc69db059e691f25c41c35c8a4cbfb46f266dcd5e47d7ea11fa322a85757db9e155212ea23

test:
  secret_key_base: d9e9bc42c58fb903f47939f86a52c118b434215d536f2c286ef35a23caf500fcdf84b0f8fde75ce104961fcc518ed94b3b6200ba54f659fad670d04ae1f973e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
